import React from 'react'
import { Divider, experimentalStyled, Tooltip, Typography } from '@material-ui/core'
import List from '@material-ui/core/List';
import ListItem from '@material-ui/core/ListItem';
import ListItemAvatar from '@material-ui/core/ListItemAvatar';
import ListItemText from '@material-ui/core/ListItemText';
import Avatar from '@material-ui/core/Avatar';


const convs = [
    {
        name: 'Shweta Surya Sha',
        phone: '02225333838',
        text: "I'll be in the neighbourhood this week.",
        person: 'https://material-ui.com/static/images/avatar/5.jpg',
    },
    {
        name: 'Karim Pai',
        phone: '02228940979',
        text: `Do you have a suggestion for a good present for John on his work
      anniversary.`,
        person: 'https://material-ui.com/static/images/avatar/1.jpg',
    },
    {
        name: 'Rohini Korpal',
        phone: '02512329135',
        text: 'I am try out this new BBQ recipe, I think this might be amazing',
        person: 'https://material-ui.com/static/images/avatar/2.jpg',
    },
    {
        name: 'Navami Chahal',
        phone: '0442644394',
        text: 'I have the tickets to the ReactConf for this year.',
        person: 'https://material-ui.com/static/images/avatar/3.jpg',
    },
    {
        name: '',
        phone: '04023755367',
        text: 'My appointment for the doctor was rescheduled for next Saturday.',
        person: 'https://material-ui.com/static/images/avatar/4.jpg',
    },
    {
        name: '',
        phone: '07925601064',
        text: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
        person: 'https://material-ui.com/static/images/avatar/5.jpg',
    },
    {
        name: 'Gulzar Pillai',
        phone: '07926598174',
        text: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
        person: 'https://material-ui.com/static/images/avatar/6.jpg',
    },
    {
        name: 'Shweta Surya Sha',
        phone: '02225833838',
        text: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
        person: 'https://material-ui.com/static/images/avatar/5.jpg',
    },
    {
        name: 'Karim Pai',
        phone: '02228970979',
        text: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
        person: 'https://material-ui.com/static/images/avatar/1.jpg',
    },
    {
        name: 'Rohini Korpal',
        phone: '02512349135',
        text: 'I am try out this new BBQ recipe, I think this might be amazing',
        person: 'https://material-ui.com/static/images/avatar/2.jpg',
    },
    {
        name: 'Navami Chahal',
        phone: '04426653394',
        text: 'I have the tickets to the ReactConf for this year.',
        person: 'https://material-ui.com/static/images/avatar/3.jpg',
    },
    {
        name: '',
        phone: '04028935367',
        text: 'My appointment for the doctor was rescheduled for next Saturday.',
        person: 'https://material-ui.com/static/images/avatar/4.jpg',
    },
    {
        name: '',
        phone: '07925667064',
        text: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
        person: 'https://material-ui.com/static/images/avatar/5.jpg',
    },
    {
        name: 'Gulzar Pillai',
        phone: '07926568474',
        text: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
        person: 'https://material-ui.com/static/images/avatar/6.jpg',
    },
];

export default function ConversationList() {
    return (
        <List sx={{ backgroundColor: 'white', mb: 0, overflow: 'auto', borderRight: '5px solid gainsboro', borderRightWidth: 'thin' }}>
            {convs.map((c, index) => (
                <React.Fragment key={c.phone}>
                    <ListItem button selected={index === 3}>
                        <ListItemAvatar>
                            <Avatar alt="Profile Picture" src={c.person} />
                        </ListItemAvatar>
                        <ListItemText primary={c.name === '' ? c.phone : c.name} secondary={
                            <Tooltip id={c.phone} sx={{ maxWidth: '20rem' }} placement="bottom" enterDelay={1000} title={c.text}>
                                <div style={{ overflow: "hidden", textOverflow: "ellipsis", width: '15rem' }}>
                                    <Typography noWrap component="span" variant="body2" color="textPrimary">
                                        {c.text}
                                    </Typography>
                                </div>
                            </Tooltip>
                        } />
                    </ListItem>
                    <Divider />
                </React.Fragment>
            ))}

        </List>
    )
}
